#ifndef __SLL__INTERNAL_STRING_FORMAT_H__
#define __SLL__INTERNAL_STRING_FORMAT_H__ 1



#define STRING_FORMAT_FLAG_PAD_ZERO 1
#define STRING_FORMAT_FLAG_SIGN 2
#define STRING_FORMAT_FLAG_SPACE_SIGN 4
#define STRING_FORMAT_FLAG_JUSTIFY_LEFT 8
#define STRING_FORMAT_FLAG_ALTERNATIVE_FORM 16
#define STRING_FORMAT_FLAG_PERCISION 32
#define STRING_FORMAT_FLAG_HH_BITS 64
#define STRING_FORMAT_FLAG_H_BITS 128
#define STRING_FORMAT_FLAG_L_BITS 256
#define STRING_FORMAT_FLAG_LL_BITS 512
#define STRING_FORMAT_FLAG_UPPERCASE 1024



#endif
