#ifndef __SLL_CAST_H__
#define __SLL_CAST_H__ 1



#define SLL_CONSTANT_TYPE_INT 1
#define SLL_CONSTANT_TYPE_FLOAT 2
#define SLL_CONSTANT_TYPE_CHAR 3
#define SLL_CONSTANT_TYPE_STRING 4
#define SLL_CONSTANT_TYPE_ARRAY 5
#define SLL_CONSTANT_TYPE_HANDLE 6
#define SLL_CONSTANT_TYPE_MAP 7
#define SLL_CONSTANT_TYPE_MAP_KEY 8
#define SLL_CONSTANT_TYPE_MAP_VALUE 9

#define SLL_MAX_CONSTANT_TYPE SLL_CONSTANT_TYPE_MAP_VALUE



#endif
