#ifndef __SLL_RUNTIME_OBJECT_H__
#define __SLL_RUNTIME_OBJECT_H__ 1
#include <sll/gc.h>



#define SLL_RUNTIME_OBJECT_STRUCT {1,SLL_RUNTIME_OBJECT_TYPE_INT,SLL_NO_DEBUG_DATA,.dt={.i=0}}

#define SLL_RUNTIME_OBJECT_TYPE_INT 0
#define SLL_RUNTIME_OBJECT_TYPE_FLOAT 1
#define SLL_RUNTIME_OBJECT_TYPE_CHAR 2
#define SLL_RUNTIME_OBJECT_TYPE_STRING 3
#define SLL_RUNTIME_OBJECT_TYPE_ARRAY 4
#define SLL_RUNTIME_OBJECT_TYPE_HANDLE 5
#define SLL_RUNTIME_OBJECT_TYPE_MAP 6
#define SLL_RUNTIME_OBJECT_TYPE_RESERVED0 62
#define SLL_RUNTIME_OBJECT_TYPE_RESERVED1 63

#define SLL_RUNTIME_OBJECT_FLAG_RESERVED0 64
#define SLL_RUNTIME_OBJECT_FLAG_RESERVED1 128

#define SLL_RUNTIME_OBJECT_GET_TYPE(r) ((r)->t&0x3f)
#define SLL_RUNTIME_OBJECT_IS_STORAGE(r) (((r)->t&0x3f)==SLL_RUNTIME_OBJECT_TYPE_STRING||((r)->t&0x3f)==SLL_RUNTIME_OBJECT_TYPE_ARRAY||((r)->t&0x3f)==SLL_RUNTIME_OBJECT_TYPE_MAP)



#endif
