path_classifiers:
  generated:
    - exclude: /
  test:
    - exclude: /
    - tests
queries:
  - include: "*"
  - exclude: cpp/complex-block
  - exclude: cpp/equality-on-floats
  - exclude: cpp/long-switch
  - exclude: cpp/poorly-documented-function
  - exclude: cpp/suspicious-pointer-scaling
  - exclude: cpp/use-of-goto
extraction:
  cpp:
    prepare:
      packages:
        - nasm
    index:
      build_command:
        - ./build.sh --verbose
  javascript:
    index:
      typescript: none
