queries:
  - include: "*"
  - exclude: cpp/complex-condition
  - exclude: cpp/long-switch
  - exclude: cpp/loop-variable-changed
  - exclude: cpp/poorly-documented-function
  - exclude: cpp/short-global-name
  - exclude: cpp/use-of-goto
  - exclude: cpp/world-writable-file-creation
  - exclude: py/empty-except
  - exclude: py/redundant-global-declaration
extraction:
  cpp:
    prepare:
      packages:
        - python3.8
    index:
      build_command:
        - python3.8 src/_build/main.py --verbose
  python:
    python_setup:
      version: 3
