path_classifiers:
  generated:
    - exclude: /
  test:
    - exclude: /
    - tests
queries:
  - include: "*"
  - exclude: cpp/complex-block
  - exclude: cpp/long-switch
  - exclude: cpp/poorly-documented-function
  - exclude: cpp/use-of-goto
extraction:
  cpp:
    prepare:
      packages:
        - python3.8
        - nasm
    configure:
      command:
        - alias python3=python3.8
    index:
      build_command:
        - ./build.sh --verbose
  javascript:
    index:
      typescript: none
  python:
    python_setup:
      version: 3
