queries:
  - include: "*"
  - exclude: cpp/complex-block
  - exclude: cpp/long-switch
  - exclude: cpp/poorly-documented-function
extraction:
  cpp:
    prepare:
      packages:
        - python3.8
    index:
      build_command:
        - python3.8 src/_build/main.py --verbose --extension
  javascript:
    index:
      typescript: none
  python:
    python_setup:
      version: 3
