#ifndef __SLL_INTERNAL_SERIAL_H__
#define __SLL_INTERNAL_SERIAL_H__ 1



#define STRING_COMPRESSION_MIN_LENGTH 32
#define STRING_COMPRESSION_OFFSET_BIT_COUNT 9
#define STRING_COMPRESSION_LENGTH_BIT_COUNT 4



#endif
