#ifndef __SLL_EXT_VERSION_H__
#define __SLL_EXT_VERSION_H__ 1
#include <sll.h>



#define __VERSION_STR_(x) #x
#define __VERSION_STR(x) __VERSION_STR_(x)



#define SLL_EXT_VERSION_MAJOR SLL_VERSION_MAJOR
#define SLL_EXT_VERSION_MINOR SLL_VERSION_MINOR
#define SLL_EXT_VERSION_PATCH SLL_VERSION_PATCH
#define SLL_EXT_VERSION_BUILD_TIME __TIME__
#define SLL_EXT_VERSION_BUILD_DATE __DATE__

#define SLL_EXT_VERSION_STRING __VERSION_STR(SLL_EXT_VERSION_MAJOR)"."__VERSION_STR(SLL_EXT_VERSION_MINOR)"."__VERSION_STR(SLL_EXT_VERSION_PATCH)
#define SLL_EXT_VERSION ((sll_version_t)((SLL_EXT_VERSION_MAJOR<<24)|(SLL_EXT_VERSION_MINOR<<16)|SLL_EXT_VERSION_PATCH))



#endif
