#ifndef __WINDOW__CURSOR_H__
#define __WINDOW__CURSOR_H__ 1



#define WINDOW_CURSOR_HIDDEN 0
#define WINDOW_CURSOR_DEFAULT 1
#define WINDOW_CURSOR_CROSS 2
#define WINDOW_CURSOR_I_BEAM 3
#define WINDOW_CURSOR_WAIT 4
#define WINDOW_CURSOR_BUSY 5
#define WINDOW_CURSOR_FORBIDDEN 6
#define WINDOW_CURSOR_POINTER 7
#define WINDOW_CURSOR_RESIZE_VERTICAL 8
#define WINDOW_CURSOR_RESIZE_HORIZONTAL 9
#define WINDOW_CURSOR_RESIZE_DIAGONAL_BT 10
#define WINDOW_CURSOR_RESIZE_DIAGONAL_TB 11
#define WINDOW_CURSOR_RESIZE_ALL 12
#define WINDOW_CURSOR_HELP 13

#define WINDOW_MAX_CURSOR WINDOW_CURSOR_HELP



#endif
