#ifndef __WINDOW_KEYBOARD_H__
#define __WINDOW_KEYBOARD_H__ 1
#include <stdint.h>



#define WINDOW_KEY_UNKNOWN 0
#define WINDOW_KEY_BACKSPACE 8
#define WINDOW_KEY_TAB 9
#define WINDOW_KEY_ENTER 10
#define WINDOW_KEY_ESCAPE 27
#define WINDOW_KEY_SPACE 32
#define WINDOW_KEY_APOSTROPHE 39
#define WINDOW_KEY_COMMA 44
#define WINDOW_KEY_MINUS 45
#define WINDOW_KEY_PERIOD 46
#define WINDOW_KEY_SLASH 47
#define WINDOW_KEY_0 48
#define WINDOW_KEY_1 49
#define WINDOW_KEY_2 50
#define WINDOW_KEY_3 51
#define WINDOW_KEY_4 52
#define WINDOW_KEY_5 53
#define WINDOW_KEY_6 54
#define WINDOW_KEY_7 55
#define WINDOW_KEY_8 56
#define WINDOW_KEY_9 57
#define WINDOW_KEY_SEMICOLON 59
#define WINDOW_KEY_EQUAL 61
#define WINDOW_KEY_A 65
#define WINDOW_KEY_B 66
#define WINDOW_KEY_C 67
#define WINDOW_KEY_D 68
#define WINDOW_KEY_E 69
#define WINDOW_KEY_F 70
#define WINDOW_KEY_G 71
#define WINDOW_KEY_H 72
#define WINDOW_KEY_I 73
#define WINDOW_KEY_J 74
#define WINDOW_KEY_K 75
#define WINDOW_KEY_L 76
#define WINDOW_KEY_M 77
#define WINDOW_KEY_N 78
#define WINDOW_KEY_O 79
#define WINDOW_KEY_P 80
#define WINDOW_KEY_Q 81
#define WINDOW_KEY_R 82
#define WINDOW_KEY_S 83
#define WINDOW_KEY_T 84
#define WINDOW_KEY_U 85
#define WINDOW_KEY_V 86
#define WINDOW_KEY_W 87
#define WINDOW_KEY_X 88
#define WINDOW_KEY_Y 89
#define WINDOW_KEY_Z 90
#define WINDOW_KEY_LEFT_BRACKET 91
#define WINDOW_KEY_BACKSLASH 92
#define WINDOW_KEY_RIGHT_BRACKET 93
#define WINDOW_KEY_GRAVE_ACCENT 96
#define WINDOW_KEY_OTHER_1 128
#define WINDOW_KEY_OTHER_2 129
#define WINDOW_KEY_F1 130
#define WINDOW_KEY_F2 131
#define WINDOW_KEY_F3 132
#define WINDOW_KEY_F4 133
#define WINDOW_KEY_F5 134
#define WINDOW_KEY_F6 135
#define WINDOW_KEY_F7 136
#define WINDOW_KEY_F8 137
#define WINDOW_KEY_F9 138
#define WINDOW_KEY_F10 139
#define WINDOW_KEY_F11 140
#define WINDOW_KEY_F12 141
#define WINDOW_KEY_F13 142
#define WINDOW_KEY_F14 143
#define WINDOW_KEY_F15 144
#define WINDOW_KEY_F16 145
#define WINDOW_KEY_F17 146
#define WINDOW_KEY_F18 147
#define WINDOW_KEY_F19 148
#define WINDOW_KEY_F20 149
#define WINDOW_KEY_F21 150
#define WINDOW_KEY_F22 151
#define WINDOW_KEY_F23 152
#define WINDOW_KEY_F24 153
#define WINDOW_KEY_F25 154
#define WINDOW_KEY_UP 155
#define WINDOW_KEY_DOWN 156
#define WINDOW_KEY_LEFT 157
#define WINDOW_KEY_RIGHT 158
#define WINDOW_KEY_INSERT 159
#define WINDOW_KEY_DELETE 160
#define WINDOW_KEY_PAGE_UP 161
#define WINDOW_KEY_PAGE_DOWN 162
#define WINDOW_KEY_HOME 163
#define WINDOW_KEY_END 164
#define WINDOW_KEY_CAPS_LOCK 165
#define WINDOW_KEY_SCROLL_LOCK 166
#define WINDOW_KEY_NUM_LOCK 167
#define WINDOW_KEY_PRINT_SCREEN 168
#define WINDOW_KEY_PAUSE 169
#define WINDOW_KEY_KEYPAD_0 170
#define WINDOW_KEY_KEYPAD_1 171
#define WINDOW_KEY_KEYPAD_2 172
#define WINDOW_KEY_KEYPAD_3 173
#define WINDOW_KEY_KEYPAD_4 174
#define WINDOW_KEY_KEYPAD_5 175
#define WINDOW_KEY_KEYPAD_6 176
#define WINDOW_KEY_KEYPAD_7 177
#define WINDOW_KEY_KEYPAD_8 178
#define WINDOW_KEY_KEYPAD_9 179
#define WINDOW_KEY_KEYPAD_DECIMAL 180
#define WINDOW_KEY_KEYPAD_DIVIDE 181
#define WINDOW_KEY_KEYPAD_MULTIPLY 182
#define WINDOW_KEY_KEYPAD_SUBTRACT 183
#define WINDOW_KEY_KEYPAD_ADD 184
#define WINDOW_KEY_KEYPAD_ENTER 185
#define WINDOW_KEY_KEYPAD_EQUAL 186
#define WINDOW_KEY_LEFT_SHIFT 187
#define WINDOW_KEY_LEFT_CONTROL 188
#define WINDOW_KEY_LEFT_ALT 189
#define WINDOW_KEY_LEFT_SUPER 190
#define WINDOW_KEY_RIGHT_SHIFT 191
#define WINDOW_KEY_RIGHT_CONTROL 192
#define WINDOW_KEY_RIGHT_ALT 193
#define WINDOW_KEY_RIGHT_SUPER 194
#define WINDOW_KEY_MENU 195

#define WINDOW_MAX_KEY WINDOW_KEY_MENU



typedef uint16_t window_key_t;



typedef uint16_t window_scan_code_t;



extern window_key_t _scancode_to_keycode[512];
extern window_scan_code_t _keycode_to_scancode[WINDOW_MAX_KEY+1];



void _setup_key_mapping(void);



#endif
