#include <sll/_sll_internal.h>
#include <sll/common.h>
#include <sll/constants.h>
#include <sll/gc.h>
#include <sll/operator.h>
#include <sll/static_object.h>
#include <sll/string.h>
#include <sll/types.h>
#include <string.h>



#define COMBINE_TYPES(a,b) (((unsigned int)(a)<<8)|(b))
#define COMBINED_TYPE_II COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_INT,SLL_RUNTIME_OBJECT_TYPE_INT)
#define COMBINED_TYPE_IF COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_INT,SLL_RUNTIME_OBJECT_TYPE_FLOAT)
#define COMBINED_TYPE_IC COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_INT,SLL_RUNTIME_OBJECT_TYPE_CHAR)
#define COMBINED_TYPE_IS COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_INT,SLL_RUNTIME_OBJECT_TYPE_STRING)
#define COMBINED_TYPE_IA COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_INT,SLL_RUNTIME_OBJECT_TYPE_ARRAY)
#define COMBINED_TYPE_FI COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_FLOAT,SLL_RUNTIME_OBJECT_TYPE_INT)
#define COMBINED_TYPE_FF COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_FLOAT,SLL_RUNTIME_OBJECT_TYPE_FLOAT)
#define COMBINED_TYPE_FC COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_FLOAT,SLL_RUNTIME_OBJECT_TYPE_CHAR)
#define COMBINED_TYPE_FS COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_FLOAT,SLL_RUNTIME_OBJECT_TYPE_STRING)
#define COMBINED_TYPE_FA COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_FLOAT,SLL_RUNTIME_OBJECT_TYPE_ARRAY)
#define COMBINED_TYPE_CI COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_CHAR,SLL_RUNTIME_OBJECT_TYPE_INT)
#define COMBINED_TYPE_CF COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_CHAR,SLL_RUNTIME_OBJECT_TYPE_FLOAT)
#define COMBINED_TYPE_CC COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_CHAR,SLL_RUNTIME_OBJECT_TYPE_CHAR)
#define COMBINED_TYPE_CS COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_CHAR,SLL_RUNTIME_OBJECT_TYPE_STRING)
#define COMBINED_TYPE_CA COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_CHAR,SLL_RUNTIME_OBJECT_TYPE_ARRAY)
#define COMBINED_TYPE_SI COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_STRING,SLL_RUNTIME_OBJECT_TYPE_INT)
#define COMBINED_TYPE_SF COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_STRING,SLL_RUNTIME_OBJECT_TYPE_FLOAT)
#define COMBINED_TYPE_SC COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_STRING,SLL_RUNTIME_OBJECT_TYPE_CHAR)
#define COMBINED_TYPE_SS COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_STRING,SLL_RUNTIME_OBJECT_TYPE_STRING)
#define COMBINED_TYPE_SA COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_STRING,SLL_RUNTIME_OBJECT_TYPE_ARRAY)
#define COMBINED_TYPE_AI COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_ARRAY,SLL_RUNTIME_OBJECT_TYPE_INT)
#define COMBINED_TYPE_AF COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_ARRAY,SLL_RUNTIME_OBJECT_TYPE_FLOAT)
#define COMBINED_TYPE_AC COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_ARRAY,SLL_RUNTIME_OBJECT_TYPE_CHAR)
#define COMBINED_TYPE_AS COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_ARRAY,SLL_RUNTIME_OBJECT_TYPE_STRING)
#define COMBINED_TYPE_AA COMBINE_TYPES(SLL_RUNTIME_OBJECT_TYPE_ARRAY,SLL_RUNTIME_OBJECT_TYPE_ARRAY)
#define COMPARE_RESULT(a,b) (a<b?SLL_COMPARE_RESULT_BELOW:(a>b?SLL_COMPARE_RESULT_ABOVE:SLL_COMPARE_RESULT_EQUAL))



__SLL_OPERATOR_UNARY(inc){
	switch (SLL_RUNTIME_OBJECT_GET_TYPE(a)){
		case SLL_RUNTIME_OBJECT_TYPE_INT:
			return SLL_FROM_INT(a->dt.i+1);
		case SLL_RUNTIME_OBJECT_TYPE_FLOAT:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_CHAR:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_STRING:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_ARRAY:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_UNARY(dec){
	switch (SLL_RUNTIME_OBJECT_GET_TYPE(a)){
		case SLL_RUNTIME_OBJECT_TYPE_INT:
			return SLL_FROM_INT(a->dt.i-1);
		case SLL_RUNTIME_OBJECT_TYPE_FLOAT:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_CHAR:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_STRING:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_ARRAY:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_BINARY(add){
	switch (COMBINE_TYPES(SLL_RUNTIME_OBJECT_GET_TYPE(a),SLL_RUNTIME_OBJECT_GET_TYPE(b))){
		case COMBINED_TYPE_II:
			return SLL_FROM_INT(a->dt.i+b->dt.i);
		case COMBINED_TYPE_IF:
			return SLL_FROM_FLOAT(a->dt.i+b->dt.f);
		case COMBINED_TYPE_IC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FI:
			return SLL_FROM_FLOAT(a->dt.f+b->dt.i);
		case COMBINED_TYPE_FF:
			return SLL_FROM_FLOAT(a->dt.f+b->dt.f);
		case COMBINED_TYPE_FC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SS:
			{
				sll_string_t sa=a->dt.s;
				sll_string_t sb=b->dt.s;
				if (!sa.l&&!sb.l){
					return SLL_ACQUIRE_STATIC(str_zero);
				}
				sll_runtime_object_t* o=SLL_CREATE();
				o->t=SLL_RUNTIME_OBJECT_TYPE_STRING;
				sll_string_create(sa.l+sb.l,&o->dt.s);
				o->dt.s.c=sa.c^sb.c;
				memcpy(o->dt.s.v,sa.v,sa.l);
				memcpy(o->dt.s.v+sa.l,sb.v,sb.l);
				return o;
			}
		case COMBINED_TYPE_SA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AA:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_BINARY(sub){
	switch (COMBINE_TYPES(SLL_RUNTIME_OBJECT_GET_TYPE(a),SLL_RUNTIME_OBJECT_GET_TYPE(b))){
		case COMBINED_TYPE_II:
			return SLL_FROM_INT(a->dt.i-b->dt.i);
		case COMBINED_TYPE_IF:
			return SLL_FROM_FLOAT(a->dt.i-b->dt.f);
		case COMBINED_TYPE_IC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FI:
			return SLL_FROM_FLOAT(a->dt.f-b->dt.i);
		case COMBINED_TYPE_FF:
			return SLL_FROM_FLOAT(a->dt.f-b->dt.f);
		case COMBINED_TYPE_FC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AA:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_BINARY(mult){
	switch (COMBINE_TYPES(SLL_RUNTIME_OBJECT_GET_TYPE(a),SLL_RUNTIME_OBJECT_GET_TYPE(b))){
		case COMBINED_TYPE_II:
			return SLL_FROM_INT(a->dt.i*b->dt.i);
		case COMBINED_TYPE_IF:
			return SLL_FROM_FLOAT(a->dt.i*b->dt.f);
		case COMBINED_TYPE_IC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FI:
			return SLL_FROM_FLOAT(a->dt.f*b->dt.i);
		case COMBINED_TYPE_FF:
			return SLL_FROM_FLOAT(a->dt.f*b->dt.f);
		case COMBINED_TYPE_FC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AA:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_BINARY(div){
	switch (COMBINE_TYPES(SLL_RUNTIME_OBJECT_GET_TYPE(a),SLL_RUNTIME_OBJECT_GET_TYPE(b))){
		case COMBINED_TYPE_II:
			return SLL_FROM_FLOAT(((sll_float_t)a->dt.i)/b->dt.i);
		case COMBINED_TYPE_IF:
			return SLL_FROM_FLOAT(a->dt.i/b->dt.f);
		case COMBINED_TYPE_IC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FI:
			return SLL_FROM_FLOAT(a->dt.f/b->dt.i);
		case COMBINED_TYPE_FF:
			return SLL_FROM_FLOAT(a->dt.f/b->dt.f);
		case COMBINED_TYPE_FC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AA:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_BINARY(floor_div){
	switch (COMBINE_TYPES(SLL_RUNTIME_OBJECT_GET_TYPE(a),SLL_RUNTIME_OBJECT_GET_TYPE(b))){
		case COMBINED_TYPE_II:
			return SLL_FROM_INT(a->dt.i/b->dt.i);
		case COMBINED_TYPE_IF:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.i/b->dt.f));
		case COMBINED_TYPE_IC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FI:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.f/b->dt.i));
		case COMBINED_TYPE_FF:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.f/b->dt.f));
		case COMBINED_TYPE_FC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AA:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_BINARY(mod){
	switch (COMBINE_TYPES(SLL_RUNTIME_OBJECT_GET_TYPE(a),SLL_RUNTIME_OBJECT_GET_TYPE(b))){
		case COMBINED_TYPE_II:
			return SLL_FROM_INT(a->dt.i%b->dt.i);
		case COMBINED_TYPE_IF:
			return SLL_FROM_INT(a->dt.i%SLL_ROUND_FLOAT(b->dt.f));
		case COMBINED_TYPE_IC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FI:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.f)%b->dt.i);
		case COMBINED_TYPE_FF:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.f)%SLL_ROUND_FLOAT(b->dt.f));
		case COMBINED_TYPE_FC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AA:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_BINARY(and){
	switch (COMBINE_TYPES(SLL_RUNTIME_OBJECT_GET_TYPE(a),SLL_RUNTIME_OBJECT_GET_TYPE(b))){
		case COMBINED_TYPE_II:
			return SLL_FROM_INT(a->dt.i&b->dt.i);
		case COMBINED_TYPE_IF:
			return SLL_FROM_INT(a->dt.i&SLL_ROUND_FLOAT(b->dt.f));
		case COMBINED_TYPE_IC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FI:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.f)&b->dt.i);
		case COMBINED_TYPE_FF:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.f)&SLL_ROUND_FLOAT(b->dt.f));
		case COMBINED_TYPE_FC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AA:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_BINARY(or){
	switch (COMBINE_TYPES(SLL_RUNTIME_OBJECT_GET_TYPE(a),SLL_RUNTIME_OBJECT_GET_TYPE(b))){
	case COMBINED_TYPE_II:
			return SLL_FROM_INT(a->dt.i|b->dt.i);
		case COMBINED_TYPE_IF:
			return SLL_FROM_INT(a->dt.i|SLL_ROUND_FLOAT(b->dt.f));
		case COMBINED_TYPE_IC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FI:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.f)|b->dt.i);
		case COMBINED_TYPE_FF:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.f)|SLL_ROUND_FLOAT(b->dt.f));
		case COMBINED_TYPE_FC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AA:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_BINARY(xor){
	switch (COMBINE_TYPES(SLL_RUNTIME_OBJECT_GET_TYPE(a),SLL_RUNTIME_OBJECT_GET_TYPE(b))){
		case COMBINED_TYPE_II:
			return SLL_FROM_INT(a->dt.i^b->dt.i);
		case COMBINED_TYPE_IF:
			return SLL_FROM_INT(a->dt.i^SLL_ROUND_FLOAT(b->dt.f));
		case COMBINED_TYPE_IC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FI:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.f)^b->dt.i);
		case COMBINED_TYPE_FF:
			return SLL_FROM_INT(SLL_ROUND_FLOAT(a->dt.f)^SLL_ROUND_FLOAT(b->dt.f));
		case COMBINED_TYPE_FC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AA:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_UNARY(inv){
	switch (SLL_RUNTIME_OBJECT_GET_TYPE(a)){
		case SLL_RUNTIME_OBJECT_TYPE_INT:
			return SLL_FROM_INT(~a->dt.i);
		case SLL_RUNTIME_OBJECT_TYPE_FLOAT:
			return SLL_FROM_INT(~SLL_ROUND_FLOAT(a->dt.f));
		case SLL_RUNTIME_OBJECT_TYPE_CHAR:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_STRING:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_ARRAY:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_UNARY(len){
	switch (SLL_RUNTIME_OBJECT_GET_TYPE(a)){
		case SLL_RUNTIME_OBJECT_TYPE_INT:
		case SLL_RUNTIME_OBJECT_TYPE_FLOAT:
		case SLL_RUNTIME_OBJECT_TYPE_CHAR:
			SLL_RETURN_ZERO;
		case SLL_RUNTIME_OBJECT_TYPE_STRING:
			return SLL_FROM_INT(a->dt.s.l);
		case SLL_RUNTIME_OBJECT_TYPE_ARRAY:
			return SLL_FROM_INT(a->dt.a.l);
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_UNARY(dup){
	switch (SLL_RUNTIME_OBJECT_GET_TYPE(a)){
		case SLL_RUNTIME_OBJECT_TYPE_INT:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_FLOAT:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_CHAR:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_STRING:
			SLL_UNIMPLEMENTED();
		case SLL_RUNTIME_OBJECT_TYPE_ARRAY:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_BINARY(access){
	if (SLL_RUNTIME_OBJECT_GET_TYPE(a)==SLL_RUNTIME_OBJECT_TYPE_STRING){
		if (SLL_RUNTIME_OBJECT_GET_TYPE(b)==SLL_RUNTIME_OBJECT_TYPE_INT){
			if (b->dt.i>=0&&b->dt.i<a->dt.s.l){
				sll_runtime_object_t* o=SLL_CREATE();
				o->t=SLL_RUNTIME_OBJECT_TYPE_CHAR;
				o->dt.c=a->dt.s.v[b->dt.i];
				return o;
			}
		}
	}
	if (SLL_RUNTIME_OBJECT_GET_TYPE(a)==SLL_RUNTIME_OBJECT_TYPE_ARRAY){
		if (SLL_RUNTIME_OBJECT_GET_TYPE(b)==SLL_RUNTIME_OBJECT_TYPE_INT){
			if (b->dt.i>=0&&b->dt.i<a->dt.a.l){
				sll_runtime_object_t* o=a->dt.a.v[b->dt.i];
				SLL_ACQUIRE(o);
				return o;
			}
		}
	}
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_TERNARY(access_range){
	SLL_UNIMPLEMENTED();
	SLL_RETURN_ZERO;
}



__SLL_OPERATOR_QUATERNARY(access_range_step){
	SLL_UNIMPLEMENTED();
	SLL_RETURN_ZERO;
}



__SLL_FUNC __SLL_RETURN_COMPARE sll_operator_compare(const sll_runtime_object_t* a,const sll_runtime_object_t* b){
	switch (COMBINE_TYPES(SLL_RUNTIME_OBJECT_GET_TYPE(a),SLL_RUNTIME_OBJECT_GET_TYPE(b))){
		case COMBINED_TYPE_II:
			return COMPARE_RESULT(a->dt.i,b->dt.i);
		case COMBINED_TYPE_IF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_IA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_FA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_CA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_SA:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AI:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AF:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AC:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AS:
			SLL_UNIMPLEMENTED();
		case COMBINED_TYPE_AA:
			SLL_UNIMPLEMENTED();
		default:
			SLL_UNREACHABLE();
	}
	return 0;
}



__SLL_FUNC __SLL_RETURN_COMPARE sll_operator_bool(const sll_runtime_object_t* a){
	switch (SLL_RUNTIME_OBJECT_GET_TYPE(a)){
		case SLL_RUNTIME_OBJECT_TYPE_INT:
			return (a->dt.i?SLL_COMPARE_RESULT_NONZERO:SLL_COMPARE_RESULT_ZERO);
		case SLL_RUNTIME_OBJECT_TYPE_FLOAT:
			return (a->dt.f?SLL_COMPARE_RESULT_NONZERO:SLL_COMPARE_RESULT_ZERO);
		case SLL_RUNTIME_OBJECT_TYPE_CHAR:
			return (a->dt.c?SLL_COMPARE_RESULT_NONZERO:SLL_COMPARE_RESULT_ZERO);
		case SLL_RUNTIME_OBJECT_TYPE_STRING:
			return (a->dt.s.l?SLL_COMPARE_RESULT_NONZERO:SLL_COMPARE_RESULT_ZERO);
		case SLL_RUNTIME_OBJECT_TYPE_ARRAY:
			return (a->dt.a.l?SLL_COMPARE_RESULT_NONZERO:SLL_COMPARE_RESULT_ZERO);
		default:
			SLL_UNREACHABLE();
	}
	return 0;
}
