#include <sll/array.h>
#include <sll/gc.h>
#include <sll/internal/static_object.h>
#include <sll/map.h>
#include <sll/object.h>
#include <sll/static_object.h>
#include <sll/string.h>
#include <sll/types.h>



__SLL_STATIC_INT_OBJECT(0);
__SLL_STATIC_INT_OBJECT(1);
__SLL_STATIC_INT_OBJECT(2);
__SLL_STATIC_INT_OBJECT(3);
__SLL_STATIC_INT_OBJECT(4);
__SLL_STATIC_INT_OBJECT(5);
__SLL_STATIC_INT_OBJECT(6);
__SLL_STATIC_INT_OBJECT(7);
__SLL_STATIC_INT_OBJECT(8);
__SLL_STATIC_INT_OBJECT(9);
__SLL_STATIC_INT_OBJECT(10);
__SLL_STATIC_INT_OBJECT(11);
__SLL_STATIC_INT_OBJECT(12);
__SLL_STATIC_INT_OBJECT(13);
__SLL_STATIC_INT_OBJECT(14);
__SLL_STATIC_INT_OBJECT(15);
__SLL_STATIC_INT_OBJECT(16);
__SLL_STATIC_INT_OBJECT(17);
__SLL_STATIC_INT_OBJECT(18);
__SLL_STATIC_INT_OBJECT(19);
__SLL_STATIC_INT_OBJECT(20);
__SLL_STATIC_INT_OBJECT(21);
__SLL_STATIC_INT_OBJECT(22);
__SLL_STATIC_INT_OBJECT(23);
__SLL_STATIC_INT_OBJECT(24);
__SLL_STATIC_INT_OBJECT(25);
__SLL_STATIC_INT_OBJECT(26);
__SLL_STATIC_INT_OBJECT(27);
__SLL_STATIC_INT_OBJECT(28);
__SLL_STATIC_INT_OBJECT(29);
__SLL_STATIC_INT_OBJECT(30);
__SLL_STATIC_INT_OBJECT(31);
__SLL_STATIC_INT_OBJECT(32);
__SLL_STATIC_INT_OBJECT(33);
__SLL_STATIC_INT_OBJECT(34);
__SLL_STATIC_INT_OBJECT(35);
__SLL_STATIC_INT_OBJECT(36);
__SLL_STATIC_INT_OBJECT(37);
__SLL_STATIC_INT_OBJECT(38);
__SLL_STATIC_INT_OBJECT(39);
__SLL_STATIC_INT_OBJECT(40);
__SLL_STATIC_INT_OBJECT(41);
__SLL_STATIC_INT_OBJECT(42);
__SLL_STATIC_INT_OBJECT(43);
__SLL_STATIC_INT_OBJECT(44);
__SLL_STATIC_INT_OBJECT(45);
__SLL_STATIC_INT_OBJECT(46);
__SLL_STATIC_INT_OBJECT(47);
__SLL_STATIC_INT_OBJECT(48);
__SLL_STATIC_INT_OBJECT(49);
__SLL_STATIC_INT_OBJECT(50);
__SLL_STATIC_INT_OBJECT(51);
__SLL_STATIC_INT_OBJECT(52);
__SLL_STATIC_INT_OBJECT(53);
__SLL_STATIC_INT_OBJECT(54);
__SLL_STATIC_INT_OBJECT(55);
__SLL_STATIC_INT_OBJECT(56);
__SLL_STATIC_INT_OBJECT(57);
__SLL_STATIC_INT_OBJECT(58);
__SLL_STATIC_INT_OBJECT(59);
__SLL_STATIC_INT_OBJECT(60);
__SLL_STATIC_INT_OBJECT(61);
__SLL_STATIC_INT_OBJECT(62);
__SLL_STATIC_INT_OBJECT(63);
__SLL_STATIC_INT_OBJECT(64);
__SLL_STATIC_INT_OBJECT(65);
__SLL_STATIC_INT_OBJECT(66);
__SLL_STATIC_INT_OBJECT(67);
__SLL_STATIC_INT_OBJECT(68);
__SLL_STATIC_INT_OBJECT(69);
__SLL_STATIC_INT_OBJECT(70);
__SLL_STATIC_INT_OBJECT(71);
__SLL_STATIC_INT_OBJECT(72);
__SLL_STATIC_INT_OBJECT(73);
__SLL_STATIC_INT_OBJECT(74);
__SLL_STATIC_INT_OBJECT(75);
__SLL_STATIC_INT_OBJECT(76);
__SLL_STATIC_INT_OBJECT(77);
__SLL_STATIC_INT_OBJECT(78);
__SLL_STATIC_INT_OBJECT(79);
__SLL_STATIC_INT_OBJECT(80);
__SLL_STATIC_INT_OBJECT(81);
__SLL_STATIC_INT_OBJECT(82);
__SLL_STATIC_INT_OBJECT(83);
__SLL_STATIC_INT_OBJECT(84);
__SLL_STATIC_INT_OBJECT(85);
__SLL_STATIC_INT_OBJECT(86);
__SLL_STATIC_INT_OBJECT(87);
__SLL_STATIC_INT_OBJECT(88);
__SLL_STATIC_INT_OBJECT(89);
__SLL_STATIC_INT_OBJECT(90);
__SLL_STATIC_INT_OBJECT(91);
__SLL_STATIC_INT_OBJECT(92);
__SLL_STATIC_INT_OBJECT(93);
__SLL_STATIC_INT_OBJECT(94);
__SLL_STATIC_INT_OBJECT(95);
__SLL_STATIC_INT_OBJECT(96);
__SLL_STATIC_INT_OBJECT(97);
__SLL_STATIC_INT_OBJECT(98);
__SLL_STATIC_INT_OBJECT(99);
__SLL_STATIC_INT_OBJECT(100);
__SLL_STATIC_INT_OBJECT(101);
__SLL_STATIC_INT_OBJECT(102);
__SLL_STATIC_INT_OBJECT(103);
__SLL_STATIC_INT_OBJECT(104);
__SLL_STATIC_INT_OBJECT(105);
__SLL_STATIC_INT_OBJECT(106);
__SLL_STATIC_INT_OBJECT(107);
__SLL_STATIC_INT_OBJECT(108);
__SLL_STATIC_INT_OBJECT(109);
__SLL_STATIC_INT_OBJECT(110);
__SLL_STATIC_INT_OBJECT(111);
__SLL_STATIC_INT_OBJECT(112);
__SLL_STATIC_INT_OBJECT(113);
__SLL_STATIC_INT_OBJECT(114);
__SLL_STATIC_INT_OBJECT(115);
__SLL_STATIC_INT_OBJECT(116);
__SLL_STATIC_INT_OBJECT(117);
__SLL_STATIC_INT_OBJECT(118);
__SLL_STATIC_INT_OBJECT(119);
__SLL_STATIC_INT_OBJECT(120);
__SLL_STATIC_INT_OBJECT(121);
__SLL_STATIC_INT_OBJECT(122);
__SLL_STATIC_INT_OBJECT(123);
__SLL_STATIC_INT_OBJECT(124);
__SLL_STATIC_INT_OBJECT(125);
__SLL_STATIC_INT_OBJECT(126);
__SLL_STATIC_INT_OBJECT(127);
__SLL_STATIC_INT_OBJECT(128);
__SLL_STATIC_INT_OBJECT(129);
__SLL_STATIC_INT_OBJECT(130);
__SLL_STATIC_INT_OBJECT(131);
__SLL_STATIC_INT_OBJECT(132);
__SLL_STATIC_INT_OBJECT(133);
__SLL_STATIC_INT_OBJECT(134);
__SLL_STATIC_INT_OBJECT(135);
__SLL_STATIC_INT_OBJECT(136);
__SLL_STATIC_INT_OBJECT(137);
__SLL_STATIC_INT_OBJECT(138);
__SLL_STATIC_INT_OBJECT(139);
__SLL_STATIC_INT_OBJECT(140);
__SLL_STATIC_INT_OBJECT(141);
__SLL_STATIC_INT_OBJECT(142);
__SLL_STATIC_INT_OBJECT(143);
__SLL_STATIC_INT_OBJECT(144);
__SLL_STATIC_INT_OBJECT(145);
__SLL_STATIC_INT_OBJECT(146);
__SLL_STATIC_INT_OBJECT(147);
__SLL_STATIC_INT_OBJECT(148);
__SLL_STATIC_INT_OBJECT(149);
__SLL_STATIC_INT_OBJECT(150);
__SLL_STATIC_INT_OBJECT(151);
__SLL_STATIC_INT_OBJECT(152);
__SLL_STATIC_INT_OBJECT(153);
__SLL_STATIC_INT_OBJECT(154);
__SLL_STATIC_INT_OBJECT(155);
__SLL_STATIC_INT_OBJECT(156);
__SLL_STATIC_INT_OBJECT(157);
__SLL_STATIC_INT_OBJECT(158);
__SLL_STATIC_INT_OBJECT(159);
__SLL_STATIC_INT_OBJECT(160);
__SLL_STATIC_INT_OBJECT(161);
__SLL_STATIC_INT_OBJECT(162);
__SLL_STATIC_INT_OBJECT(163);
__SLL_STATIC_INT_OBJECT(164);
__SLL_STATIC_INT_OBJECT(165);
__SLL_STATIC_INT_OBJECT(166);
__SLL_STATIC_INT_OBJECT(167);
__SLL_STATIC_INT_OBJECT(168);
__SLL_STATIC_INT_OBJECT(169);
__SLL_STATIC_INT_OBJECT(170);
__SLL_STATIC_INT_OBJECT(171);
__SLL_STATIC_INT_OBJECT(172);
__SLL_STATIC_INT_OBJECT(173);
__SLL_STATIC_INT_OBJECT(174);
__SLL_STATIC_INT_OBJECT(175);
__SLL_STATIC_INT_OBJECT(176);
__SLL_STATIC_INT_OBJECT(177);
__SLL_STATIC_INT_OBJECT(178);
__SLL_STATIC_INT_OBJECT(179);
__SLL_STATIC_INT_OBJECT(180);
__SLL_STATIC_INT_OBJECT(181);
__SLL_STATIC_INT_OBJECT(182);
__SLL_STATIC_INT_OBJECT(183);
__SLL_STATIC_INT_OBJECT(184);
__SLL_STATIC_INT_OBJECT(185);
__SLL_STATIC_INT_OBJECT(186);
__SLL_STATIC_INT_OBJECT(187);
__SLL_STATIC_INT_OBJECT(188);
__SLL_STATIC_INT_OBJECT(189);
__SLL_STATIC_INT_OBJECT(190);
__SLL_STATIC_INT_OBJECT(191);
__SLL_STATIC_INT_OBJECT(192);
__SLL_STATIC_INT_OBJECT(193);
__SLL_STATIC_INT_OBJECT(194);
__SLL_STATIC_INT_OBJECT(195);
__SLL_STATIC_INT_OBJECT(196);
__SLL_STATIC_INT_OBJECT(197);
__SLL_STATIC_INT_OBJECT(198);
__SLL_STATIC_INT_OBJECT(199);
__SLL_STATIC_INT_OBJECT(200);
__SLL_STATIC_INT_OBJECT(201);
__SLL_STATIC_INT_OBJECT(202);
__SLL_STATIC_INT_OBJECT(203);
__SLL_STATIC_INT_OBJECT(204);
__SLL_STATIC_INT_OBJECT(205);
__SLL_STATIC_INT_OBJECT(206);
__SLL_STATIC_INT_OBJECT(207);
__SLL_STATIC_INT_OBJECT(208);
__SLL_STATIC_INT_OBJECT(209);
__SLL_STATIC_INT_OBJECT(210);
__SLL_STATIC_INT_OBJECT(211);
__SLL_STATIC_INT_OBJECT(212);
__SLL_STATIC_INT_OBJECT(213);
__SLL_STATIC_INT_OBJECT(214);
__SLL_STATIC_INT_OBJECT(215);
__SLL_STATIC_INT_OBJECT(216);
__SLL_STATIC_INT_OBJECT(217);
__SLL_STATIC_INT_OBJECT(218);
__SLL_STATIC_INT_OBJECT(219);
__SLL_STATIC_INT_OBJECT(220);
__SLL_STATIC_INT_OBJECT(221);
__SLL_STATIC_INT_OBJECT(222);
__SLL_STATIC_INT_OBJECT(223);
__SLL_STATIC_INT_OBJECT(224);
__SLL_STATIC_INT_OBJECT(225);
__SLL_STATIC_INT_OBJECT(226);
__SLL_STATIC_INT_OBJECT(227);
__SLL_STATIC_INT_OBJECT(228);
__SLL_STATIC_INT_OBJECT(229);
__SLL_STATIC_INT_OBJECT(230);
__SLL_STATIC_INT_OBJECT(231);
__SLL_STATIC_INT_OBJECT(232);
__SLL_STATIC_INT_OBJECT(233);
__SLL_STATIC_INT_OBJECT(234);
__SLL_STATIC_INT_OBJECT(235);
__SLL_STATIC_INT_OBJECT(236);
__SLL_STATIC_INT_OBJECT(237);
__SLL_STATIC_INT_OBJECT(238);
__SLL_STATIC_INT_OBJECT(239);
__SLL_STATIC_INT_OBJECT(240);
__SLL_STATIC_INT_OBJECT(241);
__SLL_STATIC_INT_OBJECT(242);
__SLL_STATIC_INT_OBJECT(243);
__SLL_STATIC_INT_OBJECT(244);
__SLL_STATIC_INT_OBJECT(245);
__SLL_STATIC_INT_OBJECT(246);
__SLL_STATIC_INT_OBJECT(247);
__SLL_STATIC_INT_OBJECT(248);
__SLL_STATIC_INT_OBJECT(249);
__SLL_STATIC_INT_OBJECT(250);
__SLL_STATIC_INT_OBJECT(251);
__SLL_STATIC_INT_OBJECT(252);
__SLL_STATIC_INT_OBJECT(253);
__SLL_STATIC_INT_OBJECT(254);
__SLL_STATIC_INT_OBJECT(255);



__SLL_EXTERNAL sll_object_t* sll_static_int[256]={
	&_int_0_static_data,&_int_1_static_data,&_int_2_static_data,&_int_3_static_data,&_int_4_static_data,&_int_5_static_data,
	&_int_6_static_data,&_int_7_static_data,&_int_8_static_data,&_int_9_static_data,&_int_10_static_data,&_int_11_static_data,
	&_int_12_static_data,&_int_13_static_data,&_int_14_static_data,&_int_15_static_data,&_int_16_static_data,&_int_17_static_data,
	&_int_18_static_data,&_int_19_static_data,&_int_20_static_data,&_int_21_static_data,&_int_22_static_data,&_int_23_static_data,
	&_int_24_static_data,&_int_25_static_data,&_int_26_static_data,&_int_27_static_data,&_int_28_static_data,&_int_29_static_data,
	&_int_30_static_data,&_int_31_static_data,&_int_32_static_data,&_int_33_static_data,&_int_34_static_data,&_int_35_static_data,
	&_int_36_static_data,&_int_37_static_data,&_int_38_static_data,&_int_39_static_data,&_int_40_static_data,&_int_41_static_data,
	&_int_42_static_data,&_int_43_static_data,&_int_44_static_data,&_int_45_static_data,&_int_46_static_data,&_int_47_static_data,
	&_int_48_static_data,&_int_49_static_data,&_int_50_static_data,&_int_51_static_data,&_int_52_static_data,&_int_53_static_data,
	&_int_54_static_data,&_int_55_static_data,&_int_56_static_data,&_int_57_static_data,&_int_58_static_data,&_int_59_static_data,
	&_int_60_static_data,&_int_61_static_data,&_int_62_static_data,&_int_63_static_data,&_int_64_static_data,&_int_65_static_data,
	&_int_66_static_data,&_int_67_static_data,&_int_68_static_data,&_int_69_static_data,&_int_70_static_data,&_int_71_static_data,
	&_int_72_static_data,&_int_73_static_data,&_int_74_static_data,&_int_75_static_data,&_int_76_static_data,&_int_77_static_data,
	&_int_78_static_data,&_int_79_static_data,&_int_80_static_data,&_int_81_static_data,&_int_82_static_data,&_int_83_static_data,
	&_int_84_static_data,&_int_85_static_data,&_int_86_static_data,&_int_87_static_data,&_int_88_static_data,&_int_89_static_data,
	&_int_90_static_data,&_int_91_static_data,&_int_92_static_data,&_int_93_static_data,&_int_94_static_data,&_int_95_static_data,
	&_int_96_static_data,&_int_97_static_data,&_int_98_static_data,&_int_99_static_data,&_int_100_static_data,&_int_101_static_data,
	&_int_102_static_data,&_int_103_static_data,&_int_104_static_data,&_int_105_static_data,&_int_106_static_data,&_int_107_static_data,
	&_int_108_static_data,&_int_109_static_data,&_int_110_static_data,&_int_111_static_data,&_int_112_static_data,&_int_113_static_data,
	&_int_114_static_data,&_int_115_static_data,&_int_116_static_data,&_int_117_static_data,&_int_118_static_data,&_int_119_static_data,
	&_int_120_static_data,&_int_121_static_data,&_int_122_static_data,&_int_123_static_data,&_int_124_static_data,&_int_125_static_data,
	&_int_126_static_data,&_int_127_static_data,&_int_128_static_data,&_int_129_static_data,&_int_130_static_data,&_int_131_static_data,
	&_int_132_static_data,&_int_133_static_data,&_int_134_static_data,&_int_135_static_data,&_int_136_static_data,&_int_137_static_data,
	&_int_138_static_data,&_int_139_static_data,&_int_140_static_data,&_int_141_static_data,&_int_142_static_data,&_int_143_static_data,
	&_int_144_static_data,&_int_145_static_data,&_int_146_static_data,&_int_147_static_data,&_int_148_static_data,&_int_149_static_data,
	&_int_150_static_data,&_int_151_static_data,&_int_152_static_data,&_int_153_static_data,&_int_154_static_data,&_int_155_static_data,
	&_int_156_static_data,&_int_157_static_data,&_int_158_static_data,&_int_159_static_data,&_int_160_static_data,&_int_161_static_data,
	&_int_162_static_data,&_int_163_static_data,&_int_164_static_data,&_int_165_static_data,&_int_166_static_data,&_int_167_static_data,
	&_int_168_static_data,&_int_169_static_data,&_int_170_static_data,&_int_171_static_data,&_int_172_static_data,&_int_173_static_data,
	&_int_174_static_data,&_int_175_static_data,&_int_176_static_data,&_int_177_static_data,&_int_178_static_data,&_int_179_static_data,
	&_int_180_static_data,&_int_181_static_data,&_int_182_static_data,&_int_183_static_data,&_int_184_static_data,&_int_185_static_data,
	&_int_186_static_data,&_int_187_static_data,&_int_188_static_data,&_int_189_static_data,&_int_190_static_data,&_int_191_static_data,
	&_int_192_static_data,&_int_193_static_data,&_int_194_static_data,&_int_195_static_data,&_int_196_static_data,&_int_197_static_data,
	&_int_198_static_data,&_int_199_static_data,&_int_200_static_data,&_int_201_static_data,&_int_202_static_data,&_int_203_static_data,
	&_int_204_static_data,&_int_205_static_data,&_int_206_static_data,&_int_207_static_data,&_int_208_static_data,&_int_209_static_data,
	&_int_210_static_data,&_int_211_static_data,&_int_212_static_data,&_int_213_static_data,&_int_214_static_data,&_int_215_static_data,
	&_int_216_static_data,&_int_217_static_data,&_int_218_static_data,&_int_219_static_data,&_int_220_static_data,&_int_221_static_data,
	&_int_222_static_data,&_int_223_static_data,&_int_224_static_data,&_int_225_static_data,&_int_226_static_data,&_int_227_static_data,
	&_int_228_static_data,&_int_229_static_data,&_int_230_static_data,&_int_231_static_data,&_int_232_static_data,&_int_233_static_data,
	&_int_234_static_data,&_int_235_static_data,&_int_236_static_data,&_int_237_static_data,&_int_238_static_data,&_int_239_static_data,
	&_int_240_static_data,&_int_241_static_data,&_int_242_static_data,&_int_243_static_data,&_int_244_static_data,&_int_245_static_data,
	&_int_246_static_data,&_int_247_static_data,&_int_248_static_data,&_int_249_static_data,&_int_250_static_data,&_int_251_static_data,
	&_int_252_static_data,&_int_253_static_data,&_int_254_static_data,&_int_255_static_data
};



__SLL_STATIC_NEG_INT_OBJECT(1);
__SLL_STATIC_NEG_INT_OBJECT(2);
__SLL_STATIC_NEG_INT_OBJECT(3);
__SLL_STATIC_NEG_INT_OBJECT(4);
__SLL_STATIC_NEG_INT_OBJECT(5);
__SLL_STATIC_NEG_INT_OBJECT(6);
__SLL_STATIC_NEG_INT_OBJECT(7);
__SLL_STATIC_NEG_INT_OBJECT(8);
__SLL_STATIC_NEG_INT_OBJECT(9);
__SLL_STATIC_NEG_INT_OBJECT(10);
__SLL_STATIC_NEG_INT_OBJECT(11);
__SLL_STATIC_NEG_INT_OBJECT(12);
__SLL_STATIC_NEG_INT_OBJECT(13);
__SLL_STATIC_NEG_INT_OBJECT(14);
__SLL_STATIC_NEG_INT_OBJECT(15);
__SLL_STATIC_NEG_INT_OBJECT(16);



__SLL_EXTERNAL sll_object_t* sll_static_negative_int[16]={
	&_int_neg_1_static_data,&_int_neg_2_static_data,&_int_neg_3_static_data,&_int_neg_4_static_data,&_int_neg_5_static_data,
	&_int_neg_6_static_data,&_int_neg_7_static_data,&_int_neg_8_static_data,&_int_neg_9_static_data,&_int_neg_10_static_data,
	&_int_neg_11_static_data,&_int_neg_12_static_data,&_int_neg_13_static_data,&_int_neg_14_static_data,&_int_neg_15_static_data,
	&_int_neg_16_static_data
};



__SLL_STATIC_OBJECT(float_zero,SLL_OBJECT_TYPE_FLOAT,f,0);



__SLL_STATIC_OBJECT(float_one,SLL_OBJECT_TYPE_FLOAT,f,1);



__SLL_STATIC_OBJECT(float_half,SLL_OBJECT_TYPE_FLOAT,f,0.5);



__SLL_STATIC_CHAR_OBJECT(0);
__SLL_STATIC_CHAR_OBJECT(1);
__SLL_STATIC_CHAR_OBJECT(2);
__SLL_STATIC_CHAR_OBJECT(3);
__SLL_STATIC_CHAR_OBJECT(4);
__SLL_STATIC_CHAR_OBJECT(5);
__SLL_STATIC_CHAR_OBJECT(6);
__SLL_STATIC_CHAR_OBJECT(7);
__SLL_STATIC_CHAR_OBJECT(8);
__SLL_STATIC_CHAR_OBJECT(9);
__SLL_STATIC_CHAR_OBJECT(10);
__SLL_STATIC_CHAR_OBJECT(11);
__SLL_STATIC_CHAR_OBJECT(12);
__SLL_STATIC_CHAR_OBJECT(13);
__SLL_STATIC_CHAR_OBJECT(14);
__SLL_STATIC_CHAR_OBJECT(15);
__SLL_STATIC_CHAR_OBJECT(16);
__SLL_STATIC_CHAR_OBJECT(17);
__SLL_STATIC_CHAR_OBJECT(18);
__SLL_STATIC_CHAR_OBJECT(19);
__SLL_STATIC_CHAR_OBJECT(20);
__SLL_STATIC_CHAR_OBJECT(21);
__SLL_STATIC_CHAR_OBJECT(22);
__SLL_STATIC_CHAR_OBJECT(23);
__SLL_STATIC_CHAR_OBJECT(24);
__SLL_STATIC_CHAR_OBJECT(25);
__SLL_STATIC_CHAR_OBJECT(26);
__SLL_STATIC_CHAR_OBJECT(27);
__SLL_STATIC_CHAR_OBJECT(28);
__SLL_STATIC_CHAR_OBJECT(29);
__SLL_STATIC_CHAR_OBJECT(30);
__SLL_STATIC_CHAR_OBJECT(31);
__SLL_STATIC_CHAR_OBJECT(32);
__SLL_STATIC_CHAR_OBJECT(33);
__SLL_STATIC_CHAR_OBJECT(34);
__SLL_STATIC_CHAR_OBJECT(35);
__SLL_STATIC_CHAR_OBJECT(36);
__SLL_STATIC_CHAR_OBJECT(37);
__SLL_STATIC_CHAR_OBJECT(38);
__SLL_STATIC_CHAR_OBJECT(39);
__SLL_STATIC_CHAR_OBJECT(40);
__SLL_STATIC_CHAR_OBJECT(41);
__SLL_STATIC_CHAR_OBJECT(42);
__SLL_STATIC_CHAR_OBJECT(43);
__SLL_STATIC_CHAR_OBJECT(44);
__SLL_STATIC_CHAR_OBJECT(45);
__SLL_STATIC_CHAR_OBJECT(46);
__SLL_STATIC_CHAR_OBJECT(47);
__SLL_STATIC_CHAR_OBJECT(48);
__SLL_STATIC_CHAR_OBJECT(49);
__SLL_STATIC_CHAR_OBJECT(50);
__SLL_STATIC_CHAR_OBJECT(51);
__SLL_STATIC_CHAR_OBJECT(52);
__SLL_STATIC_CHAR_OBJECT(53);
__SLL_STATIC_CHAR_OBJECT(54);
__SLL_STATIC_CHAR_OBJECT(55);
__SLL_STATIC_CHAR_OBJECT(56);
__SLL_STATIC_CHAR_OBJECT(57);
__SLL_STATIC_CHAR_OBJECT(58);
__SLL_STATIC_CHAR_OBJECT(59);
__SLL_STATIC_CHAR_OBJECT(60);
__SLL_STATIC_CHAR_OBJECT(61);
__SLL_STATIC_CHAR_OBJECT(62);
__SLL_STATIC_CHAR_OBJECT(63);
__SLL_STATIC_CHAR_OBJECT(64);
__SLL_STATIC_CHAR_OBJECT(65);
__SLL_STATIC_CHAR_OBJECT(66);
__SLL_STATIC_CHAR_OBJECT(67);
__SLL_STATIC_CHAR_OBJECT(68);
__SLL_STATIC_CHAR_OBJECT(69);
__SLL_STATIC_CHAR_OBJECT(70);
__SLL_STATIC_CHAR_OBJECT(71);
__SLL_STATIC_CHAR_OBJECT(72);
__SLL_STATIC_CHAR_OBJECT(73);
__SLL_STATIC_CHAR_OBJECT(74);
__SLL_STATIC_CHAR_OBJECT(75);
__SLL_STATIC_CHAR_OBJECT(76);
__SLL_STATIC_CHAR_OBJECT(77);
__SLL_STATIC_CHAR_OBJECT(78);
__SLL_STATIC_CHAR_OBJECT(79);
__SLL_STATIC_CHAR_OBJECT(80);
__SLL_STATIC_CHAR_OBJECT(81);
__SLL_STATIC_CHAR_OBJECT(82);
__SLL_STATIC_CHAR_OBJECT(83);
__SLL_STATIC_CHAR_OBJECT(84);
__SLL_STATIC_CHAR_OBJECT(85);
__SLL_STATIC_CHAR_OBJECT(86);
__SLL_STATIC_CHAR_OBJECT(87);
__SLL_STATIC_CHAR_OBJECT(88);
__SLL_STATIC_CHAR_OBJECT(89);
__SLL_STATIC_CHAR_OBJECT(90);
__SLL_STATIC_CHAR_OBJECT(91);
__SLL_STATIC_CHAR_OBJECT(92);
__SLL_STATIC_CHAR_OBJECT(93);
__SLL_STATIC_CHAR_OBJECT(94);
__SLL_STATIC_CHAR_OBJECT(95);
__SLL_STATIC_CHAR_OBJECT(96);
__SLL_STATIC_CHAR_OBJECT(97);
__SLL_STATIC_CHAR_OBJECT(98);
__SLL_STATIC_CHAR_OBJECT(99);
__SLL_STATIC_CHAR_OBJECT(100);
__SLL_STATIC_CHAR_OBJECT(101);
__SLL_STATIC_CHAR_OBJECT(102);
__SLL_STATIC_CHAR_OBJECT(103);
__SLL_STATIC_CHAR_OBJECT(104);
__SLL_STATIC_CHAR_OBJECT(105);
__SLL_STATIC_CHAR_OBJECT(106);
__SLL_STATIC_CHAR_OBJECT(107);
__SLL_STATIC_CHAR_OBJECT(108);
__SLL_STATIC_CHAR_OBJECT(109);
__SLL_STATIC_CHAR_OBJECT(110);
__SLL_STATIC_CHAR_OBJECT(111);
__SLL_STATIC_CHAR_OBJECT(112);
__SLL_STATIC_CHAR_OBJECT(113);
__SLL_STATIC_CHAR_OBJECT(114);
__SLL_STATIC_CHAR_OBJECT(115);
__SLL_STATIC_CHAR_OBJECT(116);
__SLL_STATIC_CHAR_OBJECT(117);
__SLL_STATIC_CHAR_OBJECT(118);
__SLL_STATIC_CHAR_OBJECT(119);
__SLL_STATIC_CHAR_OBJECT(120);
__SLL_STATIC_CHAR_OBJECT(121);
__SLL_STATIC_CHAR_OBJECT(122);
__SLL_STATIC_CHAR_OBJECT(123);
__SLL_STATIC_CHAR_OBJECT(124);
__SLL_STATIC_CHAR_OBJECT(125);
__SLL_STATIC_CHAR_OBJECT(126);
__SLL_STATIC_CHAR_OBJECT(127);
__SLL_STATIC_CHAR_OBJECT(128);
__SLL_STATIC_CHAR_OBJECT(129);
__SLL_STATIC_CHAR_OBJECT(130);
__SLL_STATIC_CHAR_OBJECT(131);
__SLL_STATIC_CHAR_OBJECT(132);
__SLL_STATIC_CHAR_OBJECT(133);
__SLL_STATIC_CHAR_OBJECT(134);
__SLL_STATIC_CHAR_OBJECT(135);
__SLL_STATIC_CHAR_OBJECT(136);
__SLL_STATIC_CHAR_OBJECT(137);
__SLL_STATIC_CHAR_OBJECT(138);
__SLL_STATIC_CHAR_OBJECT(139);
__SLL_STATIC_CHAR_OBJECT(140);
__SLL_STATIC_CHAR_OBJECT(141);
__SLL_STATIC_CHAR_OBJECT(142);
__SLL_STATIC_CHAR_OBJECT(143);
__SLL_STATIC_CHAR_OBJECT(144);
__SLL_STATIC_CHAR_OBJECT(145);
__SLL_STATIC_CHAR_OBJECT(146);
__SLL_STATIC_CHAR_OBJECT(147);
__SLL_STATIC_CHAR_OBJECT(148);
__SLL_STATIC_CHAR_OBJECT(149);
__SLL_STATIC_CHAR_OBJECT(150);
__SLL_STATIC_CHAR_OBJECT(151);
__SLL_STATIC_CHAR_OBJECT(152);
__SLL_STATIC_CHAR_OBJECT(153);
__SLL_STATIC_CHAR_OBJECT(154);
__SLL_STATIC_CHAR_OBJECT(155);
__SLL_STATIC_CHAR_OBJECT(156);
__SLL_STATIC_CHAR_OBJECT(157);
__SLL_STATIC_CHAR_OBJECT(158);
__SLL_STATIC_CHAR_OBJECT(159);
__SLL_STATIC_CHAR_OBJECT(160);
__SLL_STATIC_CHAR_OBJECT(161);
__SLL_STATIC_CHAR_OBJECT(162);
__SLL_STATIC_CHAR_OBJECT(163);
__SLL_STATIC_CHAR_OBJECT(164);
__SLL_STATIC_CHAR_OBJECT(165);
__SLL_STATIC_CHAR_OBJECT(166);
__SLL_STATIC_CHAR_OBJECT(167);
__SLL_STATIC_CHAR_OBJECT(168);
__SLL_STATIC_CHAR_OBJECT(169);
__SLL_STATIC_CHAR_OBJECT(170);
__SLL_STATIC_CHAR_OBJECT(171);
__SLL_STATIC_CHAR_OBJECT(172);
__SLL_STATIC_CHAR_OBJECT(173);
__SLL_STATIC_CHAR_OBJECT(174);
__SLL_STATIC_CHAR_OBJECT(175);
__SLL_STATIC_CHAR_OBJECT(176);
__SLL_STATIC_CHAR_OBJECT(177);
__SLL_STATIC_CHAR_OBJECT(178);
__SLL_STATIC_CHAR_OBJECT(179);
__SLL_STATIC_CHAR_OBJECT(180);
__SLL_STATIC_CHAR_OBJECT(181);
__SLL_STATIC_CHAR_OBJECT(182);
__SLL_STATIC_CHAR_OBJECT(183);
__SLL_STATIC_CHAR_OBJECT(184);
__SLL_STATIC_CHAR_OBJECT(185);
__SLL_STATIC_CHAR_OBJECT(186);
__SLL_STATIC_CHAR_OBJECT(187);
__SLL_STATIC_CHAR_OBJECT(188);
__SLL_STATIC_CHAR_OBJECT(189);
__SLL_STATIC_CHAR_OBJECT(190);
__SLL_STATIC_CHAR_OBJECT(191);
__SLL_STATIC_CHAR_OBJECT(192);
__SLL_STATIC_CHAR_OBJECT(193);
__SLL_STATIC_CHAR_OBJECT(194);
__SLL_STATIC_CHAR_OBJECT(195);
__SLL_STATIC_CHAR_OBJECT(196);
__SLL_STATIC_CHAR_OBJECT(197);
__SLL_STATIC_CHAR_OBJECT(198);
__SLL_STATIC_CHAR_OBJECT(199);
__SLL_STATIC_CHAR_OBJECT(200);
__SLL_STATIC_CHAR_OBJECT(201);
__SLL_STATIC_CHAR_OBJECT(202);
__SLL_STATIC_CHAR_OBJECT(203);
__SLL_STATIC_CHAR_OBJECT(204);
__SLL_STATIC_CHAR_OBJECT(205);
__SLL_STATIC_CHAR_OBJECT(206);
__SLL_STATIC_CHAR_OBJECT(207);
__SLL_STATIC_CHAR_OBJECT(208);
__SLL_STATIC_CHAR_OBJECT(209);
__SLL_STATIC_CHAR_OBJECT(210);
__SLL_STATIC_CHAR_OBJECT(211);
__SLL_STATIC_CHAR_OBJECT(212);
__SLL_STATIC_CHAR_OBJECT(213);
__SLL_STATIC_CHAR_OBJECT(214);
__SLL_STATIC_CHAR_OBJECT(215);
__SLL_STATIC_CHAR_OBJECT(216);
__SLL_STATIC_CHAR_OBJECT(217);
__SLL_STATIC_CHAR_OBJECT(218);
__SLL_STATIC_CHAR_OBJECT(219);
__SLL_STATIC_CHAR_OBJECT(220);
__SLL_STATIC_CHAR_OBJECT(221);
__SLL_STATIC_CHAR_OBJECT(222);
__SLL_STATIC_CHAR_OBJECT(223);
__SLL_STATIC_CHAR_OBJECT(224);
__SLL_STATIC_CHAR_OBJECT(225);
__SLL_STATIC_CHAR_OBJECT(226);
__SLL_STATIC_CHAR_OBJECT(227);
__SLL_STATIC_CHAR_OBJECT(228);
__SLL_STATIC_CHAR_OBJECT(229);
__SLL_STATIC_CHAR_OBJECT(230);
__SLL_STATIC_CHAR_OBJECT(231);
__SLL_STATIC_CHAR_OBJECT(232);
__SLL_STATIC_CHAR_OBJECT(233);
__SLL_STATIC_CHAR_OBJECT(234);
__SLL_STATIC_CHAR_OBJECT(235);
__SLL_STATIC_CHAR_OBJECT(236);
__SLL_STATIC_CHAR_OBJECT(237);
__SLL_STATIC_CHAR_OBJECT(238);
__SLL_STATIC_CHAR_OBJECT(239);
__SLL_STATIC_CHAR_OBJECT(240);
__SLL_STATIC_CHAR_OBJECT(241);
__SLL_STATIC_CHAR_OBJECT(242);
__SLL_STATIC_CHAR_OBJECT(243);
__SLL_STATIC_CHAR_OBJECT(244);
__SLL_STATIC_CHAR_OBJECT(245);
__SLL_STATIC_CHAR_OBJECT(246);
__SLL_STATIC_CHAR_OBJECT(247);
__SLL_STATIC_CHAR_OBJECT(248);
__SLL_STATIC_CHAR_OBJECT(249);
__SLL_STATIC_CHAR_OBJECT(250);
__SLL_STATIC_CHAR_OBJECT(251);
__SLL_STATIC_CHAR_OBJECT(252);
__SLL_STATIC_CHAR_OBJECT(253);
__SLL_STATIC_CHAR_OBJECT(254);
__SLL_STATIC_CHAR_OBJECT(255);



__SLL_EXTERNAL sll_object_t* sll_static_char[256]={
	&_char_0_static_data,&_char_1_static_data,&_char_2_static_data,&_char_3_static_data,&_char_4_static_data,&_char_5_static_data,
	&_char_6_static_data,&_char_7_static_data,&_char_8_static_data,&_char_9_static_data,&_char_10_static_data,&_char_11_static_data,
	&_char_12_static_data,&_char_13_static_data,&_char_14_static_data,&_char_15_static_data,&_char_16_static_data,&_char_17_static_data,
	&_char_18_static_data,&_char_19_static_data,&_char_20_static_data,&_char_21_static_data,&_char_22_static_data,&_char_23_static_data,
	&_char_24_static_data,&_char_25_static_data,&_char_26_static_data,&_char_27_static_data,&_char_28_static_data,&_char_29_static_data,
	&_char_30_static_data,&_char_31_static_data,&_char_32_static_data,&_char_33_static_data,&_char_34_static_data,&_char_35_static_data,
	&_char_36_static_data,&_char_37_static_data,&_char_38_static_data,&_char_39_static_data,&_char_40_static_data,&_char_41_static_data,
	&_char_42_static_data,&_char_43_static_data,&_char_44_static_data,&_char_45_static_data,&_char_46_static_data,&_char_47_static_data,
	&_char_48_static_data,&_char_49_static_data,&_char_50_static_data,&_char_51_static_data,&_char_52_static_data,&_char_53_static_data,
	&_char_54_static_data,&_char_55_static_data,&_char_56_static_data,&_char_57_static_data,&_char_58_static_data,&_char_59_static_data,
	&_char_60_static_data,&_char_61_static_data,&_char_62_static_data,&_char_63_static_data,&_char_64_static_data,&_char_65_static_data,
	&_char_66_static_data,&_char_67_static_data,&_char_68_static_data,&_char_69_static_data,&_char_70_static_data,&_char_71_static_data,
	&_char_72_static_data,&_char_73_static_data,&_char_74_static_data,&_char_75_static_data,&_char_76_static_data,&_char_77_static_data,
	&_char_78_static_data,&_char_79_static_data,&_char_80_static_data,&_char_81_static_data,&_char_82_static_data,&_char_83_static_data,
	&_char_84_static_data,&_char_85_static_data,&_char_86_static_data,&_char_87_static_data,&_char_88_static_data,&_char_89_static_data,
	&_char_90_static_data,&_char_91_static_data,&_char_92_static_data,&_char_93_static_data,&_char_94_static_data,&_char_95_static_data,
	&_char_96_static_data,&_char_97_static_data,&_char_98_static_data,&_char_99_static_data,&_char_100_static_data,&_char_101_static_data,
	&_char_102_static_data,&_char_103_static_data,&_char_104_static_data,&_char_105_static_data,&_char_106_static_data,&_char_107_static_data,
	&_char_108_static_data,&_char_109_static_data,&_char_110_static_data,&_char_111_static_data,&_char_112_static_data,&_char_113_static_data,
	&_char_114_static_data,&_char_115_static_data,&_char_116_static_data,&_char_117_static_data,&_char_118_static_data,&_char_119_static_data,
	&_char_120_static_data,&_char_121_static_data,&_char_122_static_data,&_char_123_static_data,&_char_124_static_data,&_char_125_static_data,
	&_char_126_static_data,&_char_127_static_data,&_char_128_static_data,&_char_129_static_data,&_char_130_static_data,&_char_131_static_data,
	&_char_132_static_data,&_char_133_static_data,&_char_134_static_data,&_char_135_static_data,&_char_136_static_data,&_char_137_static_data,
	&_char_138_static_data,&_char_139_static_data,&_char_140_static_data,&_char_141_static_data,&_char_142_static_data,&_char_143_static_data,
	&_char_144_static_data,&_char_145_static_data,&_char_146_static_data,&_char_147_static_data,&_char_148_static_data,&_char_149_static_data,
	&_char_150_static_data,&_char_151_static_data,&_char_152_static_data,&_char_153_static_data,&_char_154_static_data,&_char_155_static_data,
	&_char_156_static_data,&_char_157_static_data,&_char_158_static_data,&_char_159_static_data,&_char_160_static_data,&_char_161_static_data,
	&_char_162_static_data,&_char_163_static_data,&_char_164_static_data,&_char_165_static_data,&_char_166_static_data,&_char_167_static_data,
	&_char_168_static_data,&_char_169_static_data,&_char_170_static_data,&_char_171_static_data,&_char_172_static_data,&_char_173_static_data,
	&_char_174_static_data,&_char_175_static_data,&_char_176_static_data,&_char_177_static_data,&_char_178_static_data,&_char_179_static_data,
	&_char_180_static_data,&_char_181_static_data,&_char_182_static_data,&_char_183_static_data,&_char_184_static_data,&_char_185_static_data,
	&_char_186_static_data,&_char_187_static_data,&_char_188_static_data,&_char_189_static_data,&_char_190_static_data,&_char_191_static_data,
	&_char_192_static_data,&_char_193_static_data,&_char_194_static_data,&_char_195_static_data,&_char_196_static_data,&_char_197_static_data,
	&_char_198_static_data,&_char_199_static_data,&_char_200_static_data,&_char_201_static_data,&_char_202_static_data,&_char_203_static_data,
	&_char_204_static_data,&_char_205_static_data,&_char_206_static_data,&_char_207_static_data,&_char_208_static_data,&_char_209_static_data,
	&_char_210_static_data,&_char_211_static_data,&_char_212_static_data,&_char_213_static_data,&_char_214_static_data,&_char_215_static_data,
	&_char_216_static_data,&_char_217_static_data,&_char_218_static_data,&_char_219_static_data,&_char_220_static_data,&_char_221_static_data,
	&_char_222_static_data,&_char_223_static_data,&_char_224_static_data,&_char_225_static_data,&_char_226_static_data,&_char_227_static_data,
	&_char_228_static_data,&_char_229_static_data,&_char_230_static_data,&_char_231_static_data,&_char_232_static_data,&_char_233_static_data,
	&_char_234_static_data,&_char_235_static_data,&_char_236_static_data,&_char_237_static_data,&_char_238_static_data,&_char_239_static_data,
	&_char_240_static_data,&_char_241_static_data,&_char_242_static_data,&_char_243_static_data,&_char_244_static_data,&_char_245_static_data,
	&_char_246_static_data,&_char_247_static_data,&_char_248_static_data,&_char_249_static_data,&_char_250_static_data,&_char_251_static_data,
	&_char_252_static_data,&_char_253_static_data,&_char_254_static_data,&_char_255_static_data
};



__SLL_EXTERNAL __SLL_CHECK_OUTPUT sll_object_t* sll_int_to_object(sll_integer_t v){
	if (v>-1&&v<256){
		SLL_ACQUIRE(sll_static_int[v]);
		return sll_static_int[v];
	}
	if (v>-17&&v<0){
		SLL_ACQUIRE(sll_static_negative_int[-v-1]);
		return sll_static_negative_int[-v-1];
	}
	sll_object_t* o=sll_create_object();
	o->t=SLL_OBJECT_TYPE_INT;
	o->dt.i=v;
	return o;
}



__SLL_EXTERNAL __SLL_CHECK_OUTPUT sll_object_t* sll_float_to_object(sll_float_t v){
	if (!v){
		SLL_ACQUIRE(sll_static_float_zero);
		return sll_static_float_zero;
	}
	if (v==1){
		SLL_ACQUIRE(sll_static_float_one);
		return sll_static_float_one;
	}
	if (v==0.5){
		SLL_ACQUIRE(sll_static_float_half);
		return sll_static_float_half;
	}
	sll_object_t* o=sll_create_object();
	o->t=SLL_OBJECT_TYPE_FLOAT;
	o->dt.f=v;
	return o;
}



__SLL_EXTERNAL __SLL_CHECK_OUTPUT sll_object_t* sll_char_to_object(sll_char_t v){
	SLL_ACQUIRE(sll_static_char[v]);
	return sll_static_char[v];
}
