name: All
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions: read-all
env:
  BUILD_COMMAND: python src/_build/main.py --verbose --test --do-not-run-test
jobs:
  codeql:
    name: Analyze (CodeQL)
    needs:
      - diff
      - ubuntu
      - ubuntu-release
      - windows
      - windows-release
      - ubuntu-ext
      - ubuntu-ext-release
      - windows-ext
      - windows-ext-release
    if: always()&&!contains(needs.*.result,'failed')&&(fromJSON(needs.diff.outputs.data).ubuntu||fromJSON(needs.diff.outputs.data).windows||fromJSON(needs.diff.outputs.data).ext)&&github.event_name!='workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
      - name: Build
        run: ${{env.BUILD_COMMAND}} --extension
      - name: Analyze
        uses: github/codeql-action/analyze@v1
  diff:
    name: Calculate Commit
    runs-on: ubuntu-latest
    outputs:
      data: ${{steps.calc_diff.outputs.table}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-Up Requests
        run: pip install requests
      - name: Build
        id: calc_diff
        run: python src/_build/diff.py ubuntu=.github/workflows/all.yml,src/_build,src/include/sll,src/cli,src/sll,src/sll/platform/posix windows=.github/workflows/all.yml,src/_build,src/include/sll,src/cli,src/sll,src/sll/platform/windows ext=.github/workflows/all.yml,src/_build,src/include/sll,src/include/sll_ext,src/sll_ext web-client=.github/workflows/all.yml,src/_build,src/include/sll,src/web/client web-server=.github/workflows/all.yml,src/_build,src/web/server ${{secrets.GITHUB_TOKEN}}
  release:
    name: Create Release
    needs:
      - ubuntu-release
      - windows-release
      - ubuntu-ext-release
      - windows-ext-release
    if: github.event_name=='workflow_dispatch'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-Up Requests
        run: pip install requests
      - name: Load Assets
        uses: actions/download-artifact@v2
        with:
          path: assets
      - name: Create Release
        run: python src/_build/release.py --verbose ${{secrets.GITHUB_TOKEN}}
  ubuntu:
    name: Build Ubuntu
    needs: diff
    if: fromJSON(needs.diff.outputs.data).ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}}
      - name: Test
        run: build/run_tests
  ubuntu-release:
    name: Build Ubuntu Release
    needs: diff
    if: fromJSON(needs.diff.outputs.data).ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}} --release${{github.event_name=='workflow_dispatch'&&' --bundle --upload'||''}}
      - name: Test
        run: build/run_tests
      - name: Store Assets
        uses: actions/upload-artifact@v2
        if: github.event_name=='workflow_dispatch'
        with:
          name: release-posix
          path: posix.zip
          retention-days: 1
  ubuntu-ext:
    name: Build Ubuntu Extension
    needs:
      - diff
      - ubuntu
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).ext
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --extension --extension-only
  ubuntu-ext-release:
    name: Build Ubuntu Extension Release
    needs:
      - diff
      - ubuntu-release
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).ext
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --extension --extension-only --release${{github.event_name=='workflow_dispatch'&&' --upload'||''}}
      - name: Store Asset
        uses: actions/upload-artifact@v2
        if: github.event_name=='workflow_dispatch'
        with:
          name: release-posix-ext
          path: posix-ext.so
          retention-days: 1
  web:
    name: Build Website
    needs:
      - diff
      - ubuntu
      - ubuntu-release
      - windows
      - windows-release
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).web-client&&github.event_name=='push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --web
      - name: Store Generated Website
        uses: actions/upload-artifact@v2
        with:
          name: web-bundle
          path: web-bundle.dt
          retention-days: 1
  web-server:
    name: Upload Website Server
    needs: diff
    if: fromJSON(needs.diff.outputs.data).web-server&&github.event_name=='push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-Up Requests
        run: pip install requests
      - name: Upload
        run: python src/_build/website.py --verbose --server ${{secrets.CLOUDFLARE_ACCOUNT_ID}} ${{secrets.CLOUDFLARE_WORKER_NAME}} ${{secrets.CLOUDFLARE_TOKEN}}
  web-upload:
    name: Upload Website
    needs:
      - diff
      - web
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).web-client&&github.event_name=='push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-Up Requests
        run: pip install requests
      - name: Load Generated Website
        uses: actions/download-artifact@v2
        with:
          name: web-bundle
      - name: Upload
        run: python src/_build/website.py --verbose ${{secrets.CLOUDFLARE_ACCOUNT_ID}} ${{secrets.CLOUDFLARE_NAMESPACE_ID}} ${{secrets.CLOUDFLARE_TOKEN}}
  windows:
    name: Build Windows
    needs: diff
    if: fromJSON(needs.diff.outputs.data).windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}}
      - name: Test
        run: build/run_tests
  windows-release:
    name: Build Windows Release
    needs: diff
    if: fromJSON(needs.diff.outputs.data).windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}} --release${{github.event_name=='workflow_dispatch'&&' --bundle --upload'||''}}
      - name: Test
        run: build/run_tests
      - name: Store Assets
        uses: actions/upload-artifact@v2
        if: github.event_name=='workflow_dispatch'
        with:
          name: release-win
          path: win.zip
          retention-days: 1
  windows-ext:
    name: Build Windows Extension
    needs:
      - diff
      - windows
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).ext
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --extension --extension-only
  windows-ext-release:
    name: Build Windows Extension Release
    needs:
      - diff
      - windows-release
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).ext
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --extension --extension-only --release${{github.event_name=='workflow_dispatch'&&' --upload'||''}}
      - name: Store Asset
        uses: actions/upload-artifact@v2
        if: github.event_name=='workflow_dispatch'
        with:
          name: release-win-ext
          path: win-ext.dll
          retention-days: 1
