name: Build & Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: read-all
jobs:
  all:
    name: OS = ${{matrix.os}}, Args = 'sll${{matrix.args}}'
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        args:
          - ''
          - ' --release'
          - ' --standalone'
          - ' --standalone --release'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build
      run: python src/_build/main.py --verbose --test --do-not-start-test${{matrix.args}} __ghactions
    - name: Test
      run: build/run_tests
