name: All
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: read-all
jobs:
  diff:
    name: Diff Calculation
    runs-on: ubuntu-latest
    outputs:
      data: ${{steps.calc_diff.outputs.table}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-Up Requests
        run: pip install requests
      - name: Build
        id: calc_diff
        run: python src/_build/diff.py ${{secrets.GITHUB_TOKEN}} build-ubuntu=.github/workflows/all.yml,src/include/sll,src/_build,src/cli,src/sll,!src/sll/platform,src/sll/platform/posix.c build-windows=.github/workflows/all.yml,src/include/sll,src/_build,src/cli,src/sll,!src/sll/platform,src/sll/platform/windows.c cf-pages=.github/workflows/all.yml,src/include/sll,src/web
  ubuntu:
    name: Ubuntu${{matrix.name}}
    needs:
      - diff
    if: fromJSON(needs.diff.outputs.data).build-ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - cmd: ''
            name: ''
          - cmd: ' --release'
            name: ' Release'
          - cmd: ' --standalone'
            name: ' Standalone'
          - cmd: ' --standalone --release'
            name: ' Standalone Release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --test --do-not-run-test${{matrix.cmd}}
      - name: Test
        run: build/run_tests
  windows:
    name: Windows${{matrix.name}}
    needs:
      - diff
    if: fromJSON(needs.diff.outputs.data).build-windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - cmd: ''
            name: ''
          - cmd: ' --release'
            name: ' Release'
          - cmd: ' --standalone'
            name: ' Standalone'
          - cmd: ' --standalone --release'
            name: ' Standalone Release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --test --do-not-run-test${{matrix.cmd}} __ghactions
        shell: cmd
      - name: Test
        run: build/run_tests
  codeql:
    name: CodeQL
    needs:
      - diff
      - ubuntu
      - windows
    runs-on: ubuntu-latest
    if: always()&&(fromJSON(needs.diff.outputs.data).build-ubuntu||fromJSON(needs.diff.outputs.data).build-windows)
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
      - name: Build
        run: python src/_build/main.py --verbose --test --do-not-run-test
      - name: Analyze
        uses: github/codeql-action/analyze@v1
  cloudflare:
    name: Cloudflare Deployment
    needs:
      - diff
      - codeql
    if: always()&&fromJSON(needs.diff.outputs.data).cf-pages&&github.event_name=='push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${{secrets.CLOUDFLARE_TRIGGER_KEY}}" &> /dev/null
