name: Build & Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: read-all
jobs:
  all:
    name: Build & Test (OS = ${{matrix.os}}, Args = 'sll${{matrix.args}}')
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build (Ubuntu)
      if: matrix.os=='ubuntu-latest'
      run: python src/_build/main.py --verbose --test --do-not-start-test${{matrix.args}}
    - name: Setup Windows Environment
      if: matrix.os=='windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build (Windows)
      if: matrix.os=='windows-latest'
      run: python src/_build/main.py --verbose --test --do-not-start-test${{matrix.args}}
      shell: cmd
    - name: Test
      run: build/run_tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        args:
          - ''
          - ' --release'
          - ' --standalone'
          - ' --standalone --release'
    timeout-minutes: 5
