name: All
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: read-all
env:
  BUILD_COMMAND: python src/_build/main.py --verbose --test --do-not-run-test
jobs:
  diff:
    name: Diff Calculation
    runs-on: ubuntu-latest
    outputs:
      data: ${{steps.calc_diff.outputs.table}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-Up Requests
        run: pip install requests
      - name: Build
        id: calc_diff
        run: python src/_build/diff.py ${{secrets.GITHUB_TOKEN}} sll-build-ubuntu=.github/workflows/all.yml,src/_build,src/include/sll,src/cli,src/sll,src/sll/platform/posix sll-build-windows=.github/workflows/all.yml,src/_build,src/include/sll,src/cli,src/sll,src/sll/platform/windows sll-build-ext=.github/workflows/all.yml,src/_build,src/include/sll,src/include/sll_ext,src/sll_ext cf-pages=.github/workflows/all.yml,src/_build,src/include/sll,src/web
  ubuntu:
    name: Ubuntu
    needs: diff
    if: fromJSON(needs.diff.outputs.data).sll-build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}}
      - name: Test
        run: build/run_tests
  ubuntu-release:
    name: Ubuntu Release
    needs: diff
    if: fromJSON(needs.diff.outputs.data).sll-build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}} --release
      - name: Test
        run: build/run_tests
  ubuntu-standalone:
    name: Ubuntu Standalone
    needs: diff
    if: fromJSON(needs.diff.outputs.data).sll-build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}} --standalone
      - name: Test
        run: build/run_tests
  ubuntu-standalone-release:
    name: Ubuntu Standalone Release
    needs: diff
    if: fromJSON(needs.diff.outputs.data).sll-build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}} --standalone --release
      - name: Test
        run: build/run_tests
  windows:
    name: Windows
    needs: diff
    if: fromJSON(needs.diff.outputs.data).sll-build-windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}}
      - name: Test
        run: build/run_tests
  windows-release:
    name: Windows Release
    needs: diff
    if: fromJSON(needs.diff.outputs.data).sll-build-windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}} --release
      - name: Test
        run: build/run_tests
  windows-standalone:
    name: Windows Standalone
    needs: diff
    if: fromJSON(needs.diff.outputs.data).sll-build-windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}} --standalone
      - name: Test
        run: build/run_tests
  windows-standalone-release:
    name: Windows Standalone Release
    needs: diff
    if: fromJSON(needs.diff.outputs.data).sll-build-windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}} --standalone --release
      - name: Test
        run: build/run_tests
  cloudflare:
    name: Cloudflare Deployment
    needs:
      - diff
      - ubuntu
      - ubuntu-release
      - ubuntu-standalone
      - ubuntu-standalone-release
      - windows
      - windows-release
      - windows-standalone
      - windows-standalone-release
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).cf-pages&&github.event_name=='push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${{secrets.CLOUDFLARE_TRIGGER_KEY}}" &> /dev/null
  ubuntu-ext:
    name: Ubuntu Extension
    needs:
      - diff
      - ubuntu
      - ubuntu-standalone
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).sll-build-ext
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --extension --extension-only
  ubuntu-ext-release:
    name: Ubuntu Extension Release
    needs:
      - diff
      - ubuntu-release
      - ubuntu-standalone-release
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).sll-build-ext
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --extension --extension-only --release
  windows-ext:
    name: Windows Extension
    needs:
      - diff
      - windows
      - windows-standalone
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).sll-build-ext
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --extension --extension-only
  windows-ext-release:
    name: Windows Extension Release
    needs:
      - diff
      - windows-release
      - windows-standalone-release
    if: always()&&!contains(needs.*.result,'failed')&&fromJSON(needs.diff.outputs.data).sll-build-ext
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --extension --extension-only --release
  codeql:
    name: CodeQL
    needs:
      - diff
      - ubuntu
      - ubuntu-release
      - ubuntu-standalone
      - ubuntu-standalone-release
      - windows
      - windows-release
      - windows-standalone
      - windows-standalone-release
      - ubuntu-ext
      - ubuntu-ext-release
      - windows-ext
      - windows-ext-release
    if: always()&&!contains(needs.*.result,'failed')&&(fromJSON(needs.diff.outputs.data).sll-build-ubuntu||fromJSON(needs.diff.outputs.data).sll-build-windows||fromJSON(needs.diff.outputs.data).sll-build-ext)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
      - name: Build
        run: ${{env.BUILD_COMMAND}}
      - name: Analyze
        uses: github/codeql-action/analyze@v1
