name: All
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions: read-all
env:
  BUILD_COMMAND: python src/_build/main.py --verbose
jobs:
  codeql:
    name: Analyze code
    needs:
      - diff
      - linux
      - linux-release
      - web
      - web-server
      - windows
      - windows-release
    if: always()&&!contains(needs.*.result,'failure')&&(fromJSON(needs.diff.outputs.data).linux||fromJSON(needs.diff.outputs.data).windows)&&github.event_name!='workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python@3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Initialize codeql@1
        uses: github/codeql-action/init@v1
        with:
          languages: cpp, javascript
      - name: Build
        run: ${{env.BUILD_COMMAND}}
      - name: Analyze
        uses: github/codeql-action/analyze@v1
  diff:
    name: Calculate commit
    runs-on: ubuntu-latest
    outputs:
      data: ${{steps.calc_diff.outputs.table}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python@3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-up requests
        run: pip install requests
      - name: Build
        id: calc_diff
        run: python src/_build/diff.py linux=src/sll/include,src/cli,src/sll,src/sll/platform/linux,sll/ext,tests windows=src/sll/include,src/cli,src/sll,src/sll/platform/windows,sll/ext,tests web-client=src/sll/include,src/web/client web-server=src/web/server ${{secrets.GITHUB_TOKEN}}
  linux:
    name: Build linux
    needs: diff
    if: fromJSON(needs.diff.outputs.data).linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python@3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}}
  linux-release:
    name: Build linux release
    needs: diff
    if: fromJSON(needs.diff.outputs.data).linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python@3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}} --release --bundle --upload
      - name: Store assets
        uses: actions/upload-artifact@v2
        with:
          name: release-linux
          path: |
            *.zip
          retention-days: 1
  linux-test:
    name: Test linux release
    needs:
      - diff
      - linux-release
    if: always()&&!contains(needs.*.result,'failure')&&fromJSON(needs.diff.outputs.data).linux&&github.event_name!='workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download release build
        uses: actions/download-artifact@v2
        with:
          name: release-linux
          path: build
      - name: Unpack release
        run: |
          unzip -n -o build/linux.zip -d build
          unzip -n -o build/linux_ext_debug.zip -d build\_debug_ext
          rsync --ignore-existing build\_debug_ext build
      - name: Test
        run: build/sll tests/_runner.sll
  release:
    name: Create release
    needs:
      - linux-release
      - windows-release
    if: github.event_name=='workflow_dispatch'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python@3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-up requests
        run: pip install requests
      - name: Load assets
        uses: actions/download-artifact@v2
        with:
          path: assets
      - name: Create release
        run: python src/_build/release.py --verbose ${{secrets.GITHUB_TOKEN}}
  web:
    name: Build website
    needs:
      - diff
      - linux
      - linux-release
      - windows
      - windows-release
    if: always()&&!contains(needs.*.result,'failure')&&fromJSON(needs.diff.outputs.data).web-client&&github.event_name=='push'
    runs-on: ubuntu-latest
    env:
      ANALYTICS: ${{secrets.ANALYTICS_CODE}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python@3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --web
      - name: Store generated website
        uses: actions/upload-artifact@v2
        with:
          name: web-bundle
          path: web-bundle.dt
          retention-days: 1
  web-server:
    name: Upload website server
    needs: diff
    if: fromJSON(needs.diff.outputs.data).web-server&&github.event_name=='push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python@3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-up requests
        run: pip install requests
      - name: Upload
        run: python src/_build/website.py --verbose --server ${{secrets.CLOUDFLARE_ACCOUNT_ID}} ${{secrets.CLOUDFLARE_WORKER_NAME}} ${{secrets.CLOUDFLARE_TOKEN}}
  web-upload:
    name: Upload website
    needs: web
    if: github.event_name=='push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python@3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-up requests
        run: pip install requests
      - name: Load generated website
        uses: actions/download-artifact@v2
        with:
          name: web-bundle
      - name: Upload
        run: python src/_build/website.py --verbose ${{secrets.CLOUDFLARE_ACCOUNT_ID}} ${{secrets.CLOUDFLARE_NAMESPACE_ID}} ${{secrets.CLOUDFLARE_TOKEN}}
  windows:
    name: Build windows
    needs: diff
    if: fromJSON(needs.diff.outputs.data).windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python@3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}}
  windows-release:
    name: Build windows release
    needs: diff
    if: fromJSON(needs.diff.outputs.data).windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python@3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: ${{env.BUILD_COMMAND}} --release --bundle --upload
      - name: Store assets
        uses: actions/upload-artifact@v2
        with:
          name: release-win
          path: |
            *.zip
          retention-days: 1
  windows-test:
    name: Test windows release
    needs:
      - diff
      - windows-release
    if: always()&&!contains(needs.*.result,'failure')&&fromJSON(needs.diff.outputs.data).windows&&github.event_name!='workflow_dispatch'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download release build
        uses: actions/download-artifact@v2
        with:
          name: release-win
          path: build
      - name: Unpack release
        run: |
          Expand-Archive -Force 'build\win.zip' 'build\'
          Expand-Archive -Force 'build\win_ext_debug.zip' ' build\_debug_ext\'
          robocopy /move "build\_debug_ext" "build" *
        shell: powershell
      - name: Test
        run: build/sll.exe tests/_runner.sll
