name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: read-all
jobs:
  ubuntu:
    name: Ubuntu, Args = 'sll${{matrix.args}}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        args:
          - ''
          - ' --release'
          - ' --standalone'
          - ' --standalone --release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --test --do-not-run-test${{matrix.args}}
      - name: Test
        run: build/run_tests
  windows:
    name: Windows, Args = 'sll${{matrix.args}}'
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        args:
          - ''
          - ' --release'
          - ' --standalone'
          - ' --standalone --release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --test --do-not-run-test${{matrix.args}} __ghactions
        shell: cmd
      - name: Test
        run: build/run_tests
  codeql:
    name: CodeQL
    needs:
      - ubuntu
      - windows
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
      - name: Build
        run: python src/_build/main.py --verbose --test --do-not-run-test
      - name: Analyze
        uses: github/codeql-action/analyze@v1
