name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: read-all
jobs:
  diff:
    name: Diff Calculation
    runs-on: ubuntu-latest
    outputs:
      data: ${{steps.calc_diff.outputs.table}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set-Up Requests
        run: pip install requests
      - name: Build
        id: calc_diff
        run: python src/_build/diff.py ${{secrets.GITHUB_TOKEN}} sll-build=src/_build,src/sll,src/include/sll cf-pages=src/include/sll
  ubuntu:
    name: Ubuntu, Args = 'sll${{matrix.args}}'
    needs:
      - diff
    if: fromJSON(needs.diff.outputs.data).sll-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        args:
          - ''
          - ' --release'
          - ' --standalone'
          - ' --standalone --release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --test --do-not-run-test${{matrix.args}}
      - name: Test
        run: build/run_tests
  windows:
    name: Windows, Args = 'sll${{matrix.args}}'
    needs:
      - diff
    if: fromJSON(needs.diff.outputs.data).sll-build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        args:
          - ''
          - ' --release'
          - ' --standalone'
          - ' --standalone --release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build
        run: python src/_build/main.py --verbose --test --do-not-run-test${{matrix.args}} __ghactions
        shell: cmd
      - name: Test
        run: build/run_tests
  codeql:
    name: CodeQL
    needs:
      - ubuntu
      - windows
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
      - name: Build
        run: python src/_build/main.py --verbose --test --do-not-run-test
      - name: Analyze
        uses: github/codeql-action/analyze@v1
  cloudflare:
    name: Cloudflare Deployment
    needs:
      - diff
    if: fromJSON(needs.diff.outputs.data).cf-pages
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        run: curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${{secrets.CLOUDFLARE_TRIGGER_KEY}}" &> /dev/null
